name: Rust

on:
  push:
    branches-ignore: ["dev", "next"]
    tags:
      - v*.*.*
  schedule:
    - cron: '30 9 * * 5'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust - Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup target add  wasm32-unknown-unknown wasm32-wasi --toolchain ${{ matrix.toolchain }}
      - run: cargo build --release --target wasm32-unknown-unknown
      - run: cargo test --all --all-features -v
  